apiVersion: v1
appVersion: 3.4.10
description: Centralized service for maintaining configuration information, naming,
  providing distributed synchronization, and providing group services.
home: https://zookeeper.apache.org/
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
maintainers:
- email: lachlan.evenson@microsoft.com
  name: lachie83
- email: owensk@google.com
  name: kow3ns
name: zookeeper
sources:
- https://github.com/apache/zookeeper
- https://github.com/kubernetes/contrib/tree/master/statefulsets/zookeeper
version: 1.3.1
